#ifndef PIDVALUES_H
#define PIDVALUES_H

#define DEFAULT_KP 41
#define DEFAULT_KI 0
#define DEFAULT_KD 200

#define DEFAULT_MOTOR_SPEED 230

#define DEFAULT_LOOP_DELAY 6
#define BRAKE_DURATION_MILLIS 60

#define BLUETOOTH_TUNING_ENABLED 1

#define GAPS_ENABLED 1
#define BRAKING_ENABLED 1

#define TURN_SPEED_REDUCTION_ENABLED 1
#define TURN_SPEED_REDUCTION_PERCENT 35

#define OUT_OF_LINE_ERROR_VALUE 20
#define STOP_CHECK_DELAY 130
#endif
